include:
  - project: "ifood/pipelines/gitlab-pipelines"
    ref: main
    file: "pipelines/ifood-npm-library/main.yml"

variables:
  DEFAULT_BUMP_TYPE: "patch"
  NODE_VERSION: "12.16.1"
  SERVICE_NAME: "test-gitlab-pipeline"
