name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
  # Allow manually triggering the workflow.
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Mirror to GitLab and run GitLab CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
        with:
          args: "https://code.ifoodcorp.com.br/everton.tavares/test-gitlab-pipeline"
        env:
          GITLAB_HOSTNAME: "code.ifoodcorp.com.br"
          GITLAB_USERNAME: "everton.tavares"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "10254"
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}